The "mpg" dataset, which stands for "miles per gallon". It contains information about various car models and their characteristics, such as cylinders, displacement, horsepower, weight, acceleration, model year, origin, and miles per gallon (mpg) fuel efficiency.

Here's a brief explanation of each column:

mpg: Miles per gallon, representing the fuel efficiency of the car.

cylinders: Number of cylinders in the engine.
displacement: Engine displacement, the measure of the cylinder volume swept by all of the pistons of a piston engine.

horsepower: The power of the engine, typically measured in horsepower (hp).

weight: Weight of the car, often measured in pounds.
acceleration: Acceleration of the car from 0 to 60 miles per hour (mph) in seconds.

model year: Year of manufacturing of the car model.

origin: Origin of the car, represented as a categorical 
variable (1: USA, 2: Europe, 3: Japan).

name: The name of the car model.

This dataset is commonly used for regression tasks, where the goal is to predict the fuel efficiency (mpg) of a car based on its other characteristics

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=sns.load_dataset('mpg')

In [3]:
df.shape

(398, 9)

In [4]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [5]:
df.drop("name", axis=1,inplace=True)

In [6]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [7]:
df['horsepower']=df['horsepower'].fillna(df["horsepower"].median())

In [8]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [10]:
df["origin"]

0         usa
1         usa
2         usa
3         usa
4         usa
        ...
393       usa
394    europe
395       usa
396       usa
397       usa
Name: origin, Length: 398, dtype: object

In [11]:
df["origin"].unique()

array(['usa', 'japan', 'europe'], dtype=object)

In [12]:
df["origin"].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [13]:
df['origin']=df['origin'].map({
   "usa":1,
   "japan":2,
   "europe":3 
})

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [15]:
X=df.drop("mpg",axis=1)
y=df['mpg']

In [16]:
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,3
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1
397,4,119.0,82.0,2720,19.4,82,1

In [17]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=1)

In [20]:
X_train

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
350,4,105.0,63.0,2215,14.9,81,1
59,4,97.0,54.0,2254,23.5,72,3
120,4,121.0,112.0,2868,15.5,73,3
12,8,400.0,150.0,3761,9.5,70,1
349,4,91.0,68.0,1985,16.0,81,2
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
255,4,140.0,88.0,2720,15.4,78,1
72,8,304.0,150.0,3892,12.5,72,1
235,4,97.0,75.0,2265,18.2,77,2
37,6,232.0,100.0,3288,15.5,71,1

In [21]:
X_test

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
174,6,171.0,97.0,2984,14.5,75,1
359,4,141.0,80.0,3230,20.4,81,3
250,8,318.0,140.0,3735,13.2,78,1
274,5,131.0,103.0,2830,15.9,78,3
283,6,232.0,90.0,3265,18.2,79,1
...,...,...,...,...,...,...,...
382,4,108.0,70.0,2245,16.9,82,2
39,8,400.0,175.0,4464,11.5,71,1
171,4,134.0,96.0,2702,13.5,75,2
271,4,156.0,105.0,2745,16.7,78,1
247,4,85.0,70.0,2070,18.6,78,2

In [22]:
y_train

350    34.7
59     23.0
120    19.0
12     15.0
349    34.1
       ...
393    27.0
255    25.1
72     15.0
235    26.0
37     18.0
Name: mpg, Length: 278, dtype: float64

In [23]:
y_test

174    18.0
359    28.1
250    19.4
274    20.3
283    20.2
       ...
382    34.0
39     14.0
171    24.0
271    23.2
247    39.4
Name: mpg, Length: 120, dtype: float64

In [24]:
y_train.shape

(278,)

In [25]:
y_test.shape

(120,)

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
regression_model=LinearRegression()

In [28]:
regression_model

LinearRegression()

In [29]:
regression_model.fit(X_train,y_train)

LinearRegression()

In [30]:
for i , col_name in enumerate(X_train.columns):
    print(i,col_name)

0 cylinders
1 displacement
2 horsepower
3 weight
4 acceleration
5 model_year
6 origin

In [31]:
for i , col_name in enumerate(X_train.columns):
    print(f"The coefficient for {col_name} is {regression_model.coef_[i]}")

The coefficient for cylinders is -0.3176142302799369
The coefficient for displacement is 0.026237482599078946
The coefficient for horsepower is -0.018270764913124595
The coefficient for weight is -0.007487750398361897
The coefficient for acceleration is 0.0504067346197138
The coefficient for model_year is 0.8470951427061365
The coefficient for origin is 1.5190958387975024

COEFFICIENTS ARE RELATIVE SMALLER It means if one independent variable changes slightly there will bw not much  difference in prediction

$ This is some thime called SMOOTHER model

In [32]:
from sklearn.metrics import r2_score

In [33]:
y_pred_LinearModel=regression_model.predict(X_test)

In [34]:
y_pred_LinearModel

array([21.16196121, 27.89684387, 20.45045592, 27.12361164, 24.36117063,
       15.87763934, 29.93157794, 34.02155729, 17.08992155, 10.56782304,
       30.53231377, 16.48854992, 22.4061424 , 27.76978226, 36.0209892 ,
       23.79725872, 10.82747269, 20.27707855,  8.86935273, 32.48801009,
       25.36507567, 32.75235387, 20.95486868, 24.54530695, 25.77582154,
       30.20140405, 32.01102103, 31.96692512, 15.25929349, 30.41225966,
       27.50427715, 10.93370544, 21.42816438, 28.08300976, 25.03368839,
       13.67199264, 26.67769394,  9.04050101, 32.03270673, 23.97429191,
       24.18855895, 24.60440771, 21.16368861, 34.53665774, 26.31981331,
       22.23170907, 21.0865992 , 11.65432984, 27.9398198 , 18.98058597,
       23.69821181, 26.86564242, 17.04794305, 12.03955477, 28.70876897,
       24.26227131, 10.20293895, 13.03594704, 29.96910853, 35.35029687,
       37.01162788, 35.38558158, 18.04991116, 27.90304164, 20.67174751,
       33.83899858, 27.02537633, 26.73184442, 29.93216787, 12.33895062,
       20.55262443, 22.65714109, 14.56684563, 26.56065611, 11.62492303,
       25.65879286, 28.51627153, 16.50467141, 11.74025745, 24.51069859,
       21.38744145, 20.41346334, 35.04406263, 23.94777428, 34.05299044,
       18.39944347, 15.25881993, 23.87549502, 36.12773335, 33.15643364,
       19.79370149, 22.55763359, 20.85182014, 26.88839011, 31.8751037 ,
       22.49875976, 32.61695661, 28.98417667, 23.01603316, 24.38485151,
       21.17267146,  7.56528875, 15.68250233, 33.90060931, 12.5842524 ,
       22.36320802, 31.13046288, 23.99262475, 27.92346553, 17.59905938,
       19.46074471, 30.42223204, 29.28685517, 16.84446904, 24.74015144,
       33.74072446, 10.48852524, 24.42490829, 25.6992139 , 31.14492956])

In [35]:
r2_Linear=r2_score(y_test,y_pred_LinearModel)

In [36]:
print(f"The R square value for linear regreesion is {r2_Linear}")

The R square value for linear regreesion is 0.8348001123742285

Ridge Regression

In [37]:
from sklearn.linear_model import Ridge
ridge_regression_model=Ridge(alpha=0.1)
ridge_regression_model.fit(X_train,y_train)

for i , col_name in enumerate(X_train.columns):
    print(f"The coefficient for {col_name} is {ridge_regression_model.coef_[i]}")

The coefficient for cylinders is -0.317003210100688
The coefficient for displacement is 0.026213249757983868
The coefficient for horsepower is -0.018263252481448933
The coefficient for weight is -0.007487326050213144
The coefficient for acceleration is 0.05036896947442996
The coefficient for model_year is 0.8470062938903175
The coefficient for origin is 1.5174528285653952

In [38]:
y_pred_RidgeModel=ridge_regression_model.predict(X_test)
r2_Ridge=r2_score(y_test,y_pred_RidgeModel)
print(f"The R square value for Ridge regreesion is {r2_Ridge}")

The R square value for Ridge regreesion is 0.8348084889168356

We dont see much variation in coefficient of ridge regression as compared to linear regression

Lasso

In [39]:
from sklearn.linear_model import Lasso

In [40]:
Lasso_regression_model=Lasso(alpha=0.5)
Lasso_regression_model.fit(X_train,y_train)

for i , col_name in enumerate(X_train.columns):
    print(f"The coefficient for {col_name} is {Lasso_regression_model.coef_[i]}")

The coefficient for cylinders is -0.0
The coefficient for displacement is 0.006208198888300358
The coefficient for horsepower is -0.011058382987169565
The coefficient for weight is -0.0069826731680230885
The coefficient for acceleration is 0.0
The coefficient for model_year is 0.744654952003819
The coefficient for origin is 0.0

3 features coefficients are 0 , Lasso helps in feature selection

In [41]:
y_pred_LassoModel=Lasso_regression_model.predict(X_test)
r2_Lasso=r2_score(y_test,y_pred_LassoModel)
print(f"The R square value for Ridge regreesion is {r2_Lasso}")

The R square value for Ridge regreesion is 0.8277934716635555

Elastic net

In [42]:
from sklearn.linear_model import ElasticNet

In [43]:
ElasticNet_regression_model=ElasticNet(alpha=1, l1_ratio=.5)
ElasticNet_regression_model.fit(X_train,y_train)

for i , col_name in enumerate(X_train.columns):
    print(f"The coefficient for {col_name} is {ElasticNet_regression_model.coef_[i]}")

The coefficient for cylinders is -0.0
The coefficient for displacement is 0.005888869953667563
The coefficient for horsepower is -0.012403874933570126
The coefficient for weight is -0.006934550516257631
The coefficient for acceleration is 0.0
The coefficient for model_year is 0.7133150744603874
The coefficient for origin is 0.0

In [44]:
y_pred_ElasticModel=ElasticNet_regression_model.predict(X_test)
r2_Elastic=r2_score(y_test,y_pred_ElasticModel)
print(f"The R square value for Ridge regreesion is {r2_Elastic}")

The R square value for Ridge regreesion is 0.8284840073256804

In [45]:
from sklearn.linear_model import LassoCV
lassocv=LassoCV(cv=5)
lassocv.fit(X_train,y_train)

y_pred=lassocv.predict(X_test)



score=r2_score(y_test,y_pred)
print("R2 Score", score)

R2 Score 0.8082805983844751

In [46]:
from sklearn.linear_model import RidgeCV
ridgecv=RidgeCV(cv=5)
ridgecv.fit(X_train,y_train)
y_pred=ridgecv.predict(X_test)

score=r2_score(y_test,y_pred)
print("R2 Score", score)

R2 Score 0.8354145247502055

In [47]:
ridgecv.get_params()

{'alpha_per_target': False,
 'alphas': (0.1, 1.0, 10.0),
 'cv': 5,
 'fit_intercept': True,
 'gcv_mode': None,
 'scoring': None,
 'store_cv_results': None,
 'store_cv_values': 'deprecated'}

In [48]:
from sklearn.linear_model import ElasticNetCV
elasticnetcv=ElasticNetCV(cv=5)
elasticnetcv.fit(X_train,y_train)
y_pred=elasticnetcv.predict(X_test)

score=r2_score(y_test,y_pred)
print("R2 Score", score)

R2 Score 0.792863401804916