In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import fetch_california_housing

california_df=fetch_california_housing()

In [4]:
california_df

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [5]:
print(california_df.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33 (1997) 291-297

In [6]:
df=pd.DataFrame(california_df.data,columns=california_df.feature_names)

In [7]:
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [8]:
df['target']=california_df.target

In [9]:
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [10]:
X=df.iloc[:,:-1]
y=df.target

In [14]:
df.shape

(20640, 9)

In [11]:
X.shape

(20640, 8)

In [13]:
y.shape

(20640,)

In [16]:
X.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [17]:
X.tail()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [19]:
X_train.shape

(14448, 8)

In [20]:
X_test.shape

(6192, 8)

In [21]:
from sklearn.tree import DecisionTreeRegressor

regressor=DecisionTreeRegressor()

In [22]:
regressor.fit(X_train,y_train)

DecisionTreeRegressor()

In [23]:
y_pred=regressor.predict(X_test)

In [24]:
from sklearn.metrics import r2_score
print(r2_score(y_pred,y_test))

0.6072792307079506

In [25]:
parameters={
    'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
    'splitter':['best','random'],
    'max_depth':[1,2,3,4,5,6,7,8,10,11,12],
    'max_features':['auto','sqrt','log2']
}

In [26]:
regressor=DecisionTreeRegressor()

In [27]:
from sklearn.model_selection import GridSearchCV

regressorCV=GridSearchCV(regressor,param_grid=parameters,cv=5,scoring='neg_mean_squared_error')

In [28]:
regressorCV.fit(X_train,y_train)

c:\Users\tanmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
440 fits failed out of a total of 1320.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
440 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\tanmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tanmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\tanmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\tanmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\tanmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [        nan         nan -1.18598324 -1.16620361 -0.99299057 -1.16872682
         nan         nan -0.99168457 -1.30662297 -0.87851089 -1.23031093
         nan         nan -0.91351451 -1.27931835 -0.81526387 -0.98926839
         nan         nan -0.71990642 -1.1372743  -0.69430994 -0.94668786
         nan         nan -0.7138576  -1.16420749 -0.62723963 -0.97727055
         nan         nan -0.66143757 -0.98398005 -0.52007184 -0.90474156
         nan         nan -0.57259732 -1.01929145 -0.49063468 -0.90565852
         nan         nan -0.53493615 -0.89244485 -0.47788922 -0.80337014
         nan         nan -0.50598429 -0.84074787 -0.46407142 -0.70512518
         nan         nan -0.50635362 -0.76134783 -0.46074439 -0.70017927
         nan         nan -0.50407503 -0.66764946 -0.46567183 -0.59826194
         nan         nan -1.2454422  -1.20908404 -1.19125669 -1.24472604
         nan         nan -1.08560191 -1.11713818 -0.93318021 -1.27999636
         nan         nan -0.96397591 -1.17925723 -0.79445992 -1.23593558
         nan         nan -0.79918078 -1.18506186 -0.69396501 -1.01194923
         nan         nan -0.72096991 -1.02565037 -0.60594637 -0.86813818
         nan         nan -0.61901219 -0.95061294 -0.58334864 -0.74765819
         nan         nan -0.57964932 -1.08905629 -0.51404829 -0.96589907
         nan         nan -0.50315564 -0.82721183 -0.48095515 -0.79044553
         nan         nan -0.50768857 -0.87653626 -0.4584986  -0.67937832
         nan         nan -0.52685031 -0.80749489 -0.47877569 -0.71480568
         nan         nan -0.48222977 -0.90260896 -0.46566194 -0.64045164
         nan         nan -1.15593999 -1.39533821 -1.07781977 -1.39348555
         nan         nan -0.98595963 -1.30958138 -0.92860874 -1.19668698
         nan         nan -1.01294755 -1.13858541 -0.80788659 -1.1210711
         nan         nan -0.86702869 -1.10456148 -0.73036123 -0.98019023
         nan         nan -0.76593794 -1.20151947 -0.69462878 -1.12896425
         nan         nan -0.60087482 -1.03684001 -0.60092654 -1.04336737
         nan         nan -0.68593228 -0.92903739 -0.5353145  -0.8726754
         nan         nan -0.54249982 -0.8895612  -0.510337   -0.92804628
         nan         nan -0.55015511 -1.00448828 -0.45183345 -0.71498204
         nan         nan -0.50459697 -0.85664491 -0.45021381 -0.67700614
         nan         nan -0.5307954  -0.71644049 -0.47297955 -0.69476898
         nan         nan -1.12390467 -1.2854184  -1.18336007 -1.31440375
         nan         nan -0.96127961 -1.30230832 -0.94449087 -1.20607148
         nan         nan -1.00948562 -1.09377688 -0.78336027 -1.16851478
         nan         nan -0.86305401 -1.06127466 -0.68238261 -1.02841814
         nan         nan -0.68831818 -0.97914698 -0.60470309 -0.98004041
         nan         nan -0.62815975 -1.09234141 -0.54410822 -0.84713266
         nan         nan -0.59962855 -0.86489746 -0.4982374  -0.96749585
         nan         nan -0.54816725 -0.89081507 -0.45466937 -0.85648023
         nan         nan -0.51560462 -0.82684481 -0.46656456 -0.68526043
         nan         nan -0.50122806 -0.84941908 -0.45872091 -0.64071712
         nan         nan -0.49000177 -0.72074132 -0.46305123 -0.71902883]
  warnings.warn(

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='neg_mean_squared_error')

In [29]:
regressorCV.best_params_

{'criterion': 'absolute_error',
 'max_depth': 11,
 'max_features': 'log2',
 'splitter': 'best'}

In [30]:
y_pred=regressorCV.predict(X_test)

In [31]:
print(r2_score(y_pred,y_test))

0.6383120981578927